version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  web:
    build: .
    ports:
      - "${DJANGO_EXTERNAL_PORT}:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_EXTERNAL_PORT=${DJANGO_EXTERNAL_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    stdin_open: true
    tty: true
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8080"

    depends_on:
      - redis
    networks:
      - app_network

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
